#!/bin/bash

#ARCHITECHTURE OF OS AND ITS KERNEL VERSION
arch=$(uname -a)

#NUMBER OF PHYSICAL PROCESSORS
pcpu=$(grep "physical id" /proc/cpuinfo | wc -l)

#NUMBER OF VIRTUAL PROCESSORS
vcpu=$(grep "processor" /proc/cpuinfo | wc-l)

#CURRENT AIVABLE RAM AND ITS UTILIZATION


#CURRENT AIVABLE MEMORY AND ITS UTILIZATION

#CURRENT UTILIZATION OF PROCESSORS

#DATE AND TIME OF LAST REBOOT

#LVM ACTIVITY


#ACTIVE CONNECTIONS


#USERS ON SERVER


#IPv4 ADDRESS AND ITS MAC ADDRESS


#NUMBER OF COMMANDS EXECUTED WITH THE SUDO PROGRAM

wall " #Architechture: $arch
	#CPU physical: $pcpu
	#vCPU: $vcpu
	"
